version: "3.5"

services:
  eureka:
    container_name: eureka
    build:
      context: .
      dockerfile: Dockerfile
    image: eureka:latest
    ports:
      - "8070:8070"
    networks:
      - cloud

networks:
  cloud:
    name: network_name
